import 'package:some_ride/features/home/model/car.dart';

class CarService {
  List<Car> getCarList() {
    return <Car>[
      Car(
        "Land Rover",
        "Discovery",
        1000000,
        "Weekly",
        [
          "assets/images/cars/land_rover_0.png",
          "assets/images/cars/land_rover_1.png",
          "assets/images/cars/land_rover_2.png",
        ],
        'Automatic',
      ),
      Car(
        "Alfa Romeo",
        "C4",
        3200000,
        "Monthly",
        [
          "assets/images/cars/alfa_romeo_c4_0.png",
        ],
        'Automatic',
      ),
      Car(
        "Nissan",
        "GTR",
        50000,
        "Daily",
        [
          "assets/images/cars/nissan_gtr_0.png",
          "assets/images/cars/nissan_gtr_1.png",
          "assets/images/cars/nissan_gtr_2.png",
          "assets/images/cars/nissan_gtr_3.png",
        ],
        'Automatic',
      ),
      Car(
        "Acura",
        "MDX 2020",
        1350000,
        "Monthly",
        [
          "assets/images/cars/acura_0.png",
          "assets/images/cars/acura_1.png",
          "assets/images/cars/acura_2.png",
        ],
        'Automatic',
      ),
      Car(
        "Chevrolet",
        "Camaro",
        600000,
        "Weekly",
        [
          "assets/images/cars/camaro_0.png",
          "assets/images/cars/camaro_1.png",
          "assets/images/cars/camaro_2.png",
        ],
        'Automatic',
      ),
      Car(
        "Ferrari",
        "Spider 488",
        5000000,
        "Weekly",
        [
          "assets/images/cars/ferrari_spider_488_0.png",
          "assets/images/cars/ferrari_spider_488_1.png",
          "assets/images/cars/ferrari_spider_488_2.png",
          "assets/images/cars/ferrari_spider_488_3.png",
          "assets/images/cars/ferrari_spider_488_4.png",
        ],
        'Manual',
      ),
      Car(
        "Ford",
        "Focus",
        200000,
        "Weekly",
        [
          "assets/images/cars/ford_0.png",
          "assets/images/cars/ford_1.png",
        ],
        'Automatic',
      ),
      Car(
        "Fiat",
        "500x",
        130000,
        "Weekly",
        [
          "assets/images/cars/fiat_0.png",
          "assets/images/cars/fiat_1.png",
        ],
        'Manual',
      ),
      Car(
        "Honda",
        "Civic",
        20000,
        "Daily",
        [
          "assets/images/cars/honda_0.png",
        ],
        'Automatic',
      ),
      Car(
        "Citroen",
        "Picasso",
        300000,
        "Monthly",
        [
          "assets/images/cars/citroen_0.png",
          "assets/images/cars/citroen_1.png",
          "assets/images/cars/citroen_2.png",
        ],
        'Automatic',
      ),
    ];
  }
}
