import 'package:some_ride/features/home/model/car.dart';

class CarService {
  List<Car> getCarList() {
    return <Car>[
      Car(
        "Land Rover",
        "Discovery",
        1000000,
        "Weekly",
        [
          "assets/images/cars/land_rover_0.png",
          "assets/images/cars/land_rover_1.png",
          "assets/images/cars/land_rover_2.png",
        ],
        'Automatic',
        270,
        '2000 CC',
        false,
      ),
      Car(
        "Alfa Romeo",
        "C4",
        3200000,
        "Monthly",
        [
          "assets/images/cars/alfa_romeo_c4_0.png",
        ],
        'Automatic',
        180,
        '2000 CC',
        false,
      ),
      Car(
        "Nissan",
        "GTR",
        50000,
        "Daily",
        [
          "assets/images/cars/nissan_gtr_0.png",
          "assets/images/cars/nissan_gtr_1.png",
          "assets/images/cars/nissan_gtr_2.png",
          "assets/images/cars/nissan_gtr_3.png",
        ],
        'Automatic',
        180,
        '1800 CC',
        false,
      ),
      Car(
        "Acura",
        "MDX 2020",
        1350000,
        "Monthly",
        [
          "assets/images/cars/acura_0.png",
          "assets/images/cars/acura_1.png",
          "assets/images/cars/acura_2.png",
        ],
        'Automatic',
        240,
        '2500 CC',
        false,
      ),
      Car(
        "Chevrolet",
        "Camaro",
        600000,
        "Weekly",
        [
          "assets/images/cars/camaro_0.png",
          "assets/images/cars/camaro_1.png",
          "assets/images/cars/camaro_2.png",
        ],
        'Automatic',
        180,
        '1800 CC',
        false,
      ),
      Car(
        "Ferrari",
        "Spider 488",
        5000000,
        "Weekly",
        [
          "assets/images/cars/ferrari_spider_488_0.png",
          "assets/images/cars/ferrari_spider_488_1.png",
          "assets/images/cars/ferrari_spider_488_2.png",
          "assets/images/cars/ferrari_spider_488_3.png",
          "assets/images/cars/ferrari_spider_488_4.png",
        ],
        'Manual',
        360,
        '3000 CC',
        true,
      ),
      Car(
        "Ford",
        "Focus",
        200000,
        "Weekly",
        [
          "assets/images/cars/ford_0.png",
          "assets/images/cars/ford_1.png",
        ],
        'Automatic',
        250,
        '2200 CC',
        false,
      ),
      Car(
        "Toyota",
        "Premio",
        50000,
        "Weekly",
        [
          "assets/images/cars/premio_1.png",
          "assets/images/cars/premio_2.png",
        ],
        'Automatic',
        180,
        '2000 CC',
        false,
      ),
      Car(
        "Fiat",
        "500x",
        130000,
        "Weekly",
        [
          "assets/images/cars/fiat_0.png",
          "assets/images/cars/fiat_1.png",
        ],
        'Manual',
        180,
        '1500 CC',
        false,
      ),
      Car(
        "Subaru",
        "Forester",
        150000,
        "Weekly",
        [
          "assets/images/cars/forester_0.png",
          "assets/images/cars/forester_1.png",
          "assets/images/cars/forester_2.png",
        ],
        'Automatic',
        180,
        '2200 CC',
        false,
      ),
      Car(
        "Honda",
        "CRV",
        20000,
        "Daily",
        [
          "assets/images/cars/crv_0.png",
          "assets/images/cars/crv_1.png",
        ],
        'Manual',
        180,
        '1800 CC',
        false,
      ),
      Car(
        "Honda",
        "Civic",
        20000,
        "Daily",
        [
          "assets/images/cars/honda_0.png",
        ],
        'Automatic',
        180,
        '1500 CC',
        false,
      ),
      Car(
        "Citroen",
        "Picasso",
        300000,
        "Monthly",
        [
          "assets/images/cars/citroen_0.png",
          "assets/images/cars/citroen_1.png",
          "assets/images/cars/citroen_2.png",
        ],
        'Automatic',
        180,
        '2000 CC',
        false,
      ),
    ];
  }
}
