// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA59LktN9OhMyLDJCq3huba33PbOba3vA8',
    appId: '1:764702856261:web:3b7f65a527a1405064ff2c',
    messagingSenderId: '764702856261',
    projectId: 'simbula-273cb',
    authDomain: 'simbula-273cb.firebaseapp.com',
    storageBucket: 'simbula-273cb.appspot.com',
    measurementId: 'G-NXMLFP6WRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlj8AmrR2YziFGYwlbIzexrKhcFbXwFpU',
    appId: '1:764702856261:android:979b4d55e054f04064ff2c',
    messagingSenderId: '764702856261',
    projectId: 'simbula-273cb',
    storageBucket: 'simbula-273cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbYZDaMfTA77nwojie7RK_5_kuUm07nbU',
    appId: '1:764702856261:ios:252f1190af0795e564ff2c',
    messagingSenderId: '764702856261',
    projectId: 'simbula-273cb',
    storageBucket: 'simbula-273cb.appspot.com',
    iosBundleId: 'com.keith.finalyear.someRide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbYZDaMfTA77nwojie7RK_5_kuUm07nbU',
    appId: '1:764702856261:ios:3969e1c5cd1afebc64ff2c',
    messagingSenderId: '764702856261',
    projectId: 'simbula-273cb',
    storageBucket: 'simbula-273cb.appspot.com',
    iosBundleId: 'com.keith.finalyear.someRide.RunnerTests',
  );
}
